# SPDX-License-Identifier: MIT-0
---
# tasks file for seafile-install
- name: Create working directory
  ansible.builtin.file:
    path: /opt/seafile
    state: directory
    mode: '0755'

# Upload configuration files
- name: Upload .env configuration
  ansible.builtin.copy:
    src: .env
    dest: /opt/seafile/.env
    mode: '0644'
- name: Upload seadoc docker-compose file
  ansible.builtin.copy:
    src: seadoc.yml
    dest: /opt/seafile/seadoc.yml
    mode: '0644'
- name: Upload seafile-server docker-compose file
  ansible.builtin.copy:
    src: seafile-server.yml
    dest: /opt/seafile/seafile-server.yml
    mode: '0644'
- name: Upload caddy docker-compose file
  ansible.builtin.copy:
    src: caddy.yml
    dest: /opt/seafile/caddy.yml
    mode: '0644'
# Create volume directory of Seafile data
- name: Create volume directory of Seafile data
  ansible.builtin.file:
    path: /opt/seafile-data
    state: directory
    mode: '0755'
- name: Create volume directory of MySQL data
  ansible.builtin.file:
    path: /opt/seafile-mysql/db
    state: directory
    mode: '0755'
- name: Create volume directory of Caddy data
  ansible.builtin.file:
    path: /opt/seafile-caddy/certs
    state: directory
    mode: '0755'



- name: Create volume directory of notification data
  ansible.builtin.file:
    path: /opt/notification-data
    state: directory
    mode: '0755'

# - name: Pull Docker images
#   community.docker.docker_compose:
#     project_src: /opt/seafile
#     pull: true

# - name: Start Docker containers
#   community.docker.docker_compose:
#     project_src: /opt/seafile
#     build: true
#     state: present   # или `state: started`
#     restarted: true  # правильный параметр

- name: Run docker-compose to start Seafile services
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/seafile
#   register: seafile_compose_output
#   ignore_errors: yes
