# SPDX-License-Identifier: MIT-0
---
# tasks file for seafile-install
- name: Create working directory
  ansible.builtin.file:
    path: /opt/seafile
    state: directory
    mode: '0755'

# Upload configuration files
- name: Upload .env configuration
  ansible.builtin.copy:
    src: .env
    dest: /opt/seafile/.env
    mode: '0644'
- name: Upload seadoc docker-compose file
  ansible.builtin.copy:
    src: seadoc.yml
    dest: /opt/seafile/seadoc.yml
    mode: '0644'
- name: Upload seafile-server docker-compose file
  ansible.builtin.copy:
    src: seafile-server.yml
    dest: /opt/seafile/seafile-server.yml
    mode: '0644'
- name: Upload caddy docker-compose file
  ansible.builtin.copy:
    src: caddy.yml
    dest: /opt/seafile/caddy.yml
    mode: '0644'
# Create volume directory of Seafile data
- name: Create volume directory of Seafile data
  ansible.builtin.file:
    path: /opt/seafile-data
    state: directory
    mode: '0755'
- name: Create volume directory of MySQL data
  ansible.builtin.file:
    path: /opt/seafile-mysql/db
    state: directory
    mode: '0755'
- name: Create volume directory of Caddy data
  ansible.builtin.file:
    path: /opt/seafile-caddy
    state: directory
    mode: '0755'
- name: Create volume directory of notification data
  ansible.builtin.file:
    path: /opt/notification-data
    state: directory
    mode: '0755'
#
# - name: Set SEAFILE_MYSQL_DB_HOST in "/opt/seafile/.env"
#   ansible.builtin.lineinfile:
#     path: /opt/seafile/.env
#     regexp: '^SEAFILE_MYSQL_DB_HOST.*'
#     line: 'SEAFILE_MYSQL_DB_HOST=192.168.90.4'
# - name: Set INIT_SEAFILE_MYSQL_ROOT_PASSWORD in "/opt/seafile/.env"
#   ansible.builtin.lineinfile:
#     path: /opt/seafile/.env
#     regexp: '^INIT_SEAFILE_MYSQL_ROOT_PASSWORD.*'
#     line: 'INIT_SEAFILE_MYSQL_ROOT_PASSWORD=123456'
# - name: Set SEAFILE_MYSQL_DB_PORT in "/opt/seafile/.env"
#   ansible.builtin.lineinfile:
#     path: /opt/seafile/.env
#     regexp: '^SEAFILE_MYSQL_DB_PORT.*'
#     line: 'SEAFILE_MYSQL_DB_PORT=3306'
# - name: Set SEAFILE_MYSQL_DB_PASSWORD in "/opt/seafile/.env"
#   ansible.builtin.lineinfile:
#     path: /opt/seafile/.env
#     regexp: '^SEAFILE_MYSQL_DB_PASSWORD.*'
#     line: 'SEAFILE_MYSQL_DB_PASSWORD=123456'

# - name: Set INIT_SEAFILE_MYSQL_ROOT_PASSWORD in "/opt/seafile/.env"
#   ansible.builtin.replace:
#     path: /opt/seafile/.env
#     regexp: '^INIT_SEAFILE_MYSQL_ROOT_PASSWORD.*'
#     replace: 'INIT_SEAFILE_MYSQL_ROOT_PASSWORD=123456'

# - name: Set SEAFILE_MYSQL_DB_PASSWORD in "/opt/seafile/.env"
#   ansible.builtin.replace:
#     path: /opt/seafile/.env
#     regexp: '^SEAFILE_MYSQL_DB_PASSWORD.*'
#     replace: 'SEAFILE_MYSQL_DB_PASSWORD=123456'
