---
- name: Configure monitoring-srv
  import_playbook: 8_monitoring-srv_setup.yml
- name: Configure log server vm
  import_playbook: 6_log_srv_setup.yml
- name: Configure reverse-proxy vm
  import_playbook: 2_web-01_setup.yml
- name: Configure db-01 vm
  import_playbook: 4_db-01_setup.yml
- name: Configure db-02 vm
  import_playbook: 5_db-02_setup.yml
- name: Configure seafile vm
  import_playbook: 3_web-01_setup.yml
