---
- name: Create and configure VMs on Proxmox
  hosts: pve  # Укажите ваш хост Proxmox в инвентаре
  gather_facts: no
  become: yes
  vars:
    template_id: 9000
    gateway: 192.168.90.1
    vms:
      - name: web-proxy
        vmid: 102
        ip: 192.168.90.2
      - name: web-01
        vmid: 103
        ip: 192.168.90.3
      - name: db-01
        vmid: 104
        ip: 192.168.90.4
      - name: db-02
        vmid: 105
        ip: 192.168.90.5
      - name: log-srv
        vmid: 106
        ip: 192.168.90.6
      - name: backup-srv
        vmid: 107
        ip: 192.168.90.7
      - name: monitoring-srv
        vmid: 108
        ip: 192.168.90.8

  tasks:
    - name: Clone VMs from template
      ansible.builtin.command: >
        qm clone {{ template_id }} {{ item.vmid }} 
        --name {{ item.name }} 
        --full
      ignore_errors: yes
      loop: "{{ vms }}"

    - name: Configure network settings
      ansible.builtin.command: >
        qm set {{ item.vmid }} 
        --ipconfig0 ip={{ item.ip }}/28,gw={{ gateway }}
      ignore_errors: yes
      loop: "{{ vms }}"

    - name: Start virtual machines
      ansible.builtin.command: >
        qm start {{ item.vmid }}
      ignore_errors: yes
      loop: "{{ vms }}"