---
- name: nginx | Установка и настройка nginx
  hosts: hw-rpm
  become: yes
#  vars:
#     nginx_listen_port: 8080

  tasks: 
    - name: install packages
      ansible.builtin.yum:
        name:
          - wget
          - rpmdevtools
          - rpm-build
          - createrepo
          # - yum-utilswatsh 
          - cmake
          - gcc
          - git
          - nano
        state: present
        update_cache: yes
      tags:
        - install packages
    - name: create directories
      ansible.builtin.file:
        path: rpm
        state: directory
      tags: 
        - create directories
    - name: Download nginx source RPM
      ansible.builtin.command:
        cmd: yumdownloader --source nginx
        chdir: rpm
...


