---
- name: Установка Prometheus и Grafana на Debian 12
  hosts: all
  become: true  # Выполнение от имени root
  tasks:
    - name: Обновление кэша apt
      apt:
        update_cache: yes

    - name: Установка необходимых пакетов
      apt:
        name:
          - wget
          - curl
          - software-properties-common
          - musl
        state: present

    # Установка Prometheus
    - name: Скачивание Prometheus
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Распаковка Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Создание пользователя и директорий для Prometheus
      ansible.builtin.user:
        name: prometheus
        state: present
      register: prometheus_user_created

    - name: Настройка директорий для Prometheus
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Копирование бинарных файлов Prometheus
      ansible.builtin.copy:
        src: /opt/prometheus-2.47.0.linux-amd64/prometheus
        dest: /usr/local/bin/prometheus
        remote_src: yes
        mode: '0755'

    - name: Копирование конфигурационного файла Prometheus
      ansible.builtin.copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["localhost:9090"]
            - job_name: 'node_exporter'
              static_configs:
                - targets: ["localhost:9100"]

    - name: Создание службы Prometheus
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus

          [Install]
          WantedBy=multi-user.target

    - name: Скачивание Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Распаковка Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Копирование исполняемого файла в /usr/local/bin/
      ansible.builtin.copy:
        src: "/opt/node_exporter-1.8.2.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: "0755"
        remote_src: yes

    - name: Создание пользователя nodeusr
      ansible.builtin.user:
        name: nodeusr
        shell: /bin/false
        system: yes
        create_home: no

    - name: Назначение прав на исполняемый файл
      ansible.builtin.file:
        path: /usr/local/bin/node_exporter
        owner: nodeusr
        group: nodeusr
        mode: "0755"

    - name: Создание файла службы systemd для Node Exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter Service
          After=network.target

          [Service]
          User=nodeusr
          Group=nodeusr
          Type=simple
          ExecStart=/usr/local/bin/node_exporter
          ExecReload=/bin/kill -HUP $MAINPID
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        mode: "0644"

    - name: Перезагрузка systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Включение автозапуска службы Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        enabled: yes

    - name: Запуск службы Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started

    - name: Запуск и включение автозапуска Prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: true

    - name: Скачивание Grafana
      ansible.builtin.get_url:
        url: "https://mirrors.huaweicloud.com/grafana/10.4.8/grafana-enterprise_10.4.8_amd64.deb"
        dest: /tmp/grafana.deb

    # Установка Grafana из пакета
    - name: Установка Grafana из пакета
      ansible.builtin.apt: 
        deb: "/tmp/grafana.deb"

    - name: Запуск и включение автозапуска Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: true