Vagrant.configure("2") do |config|
  MACHINES = {
    :inetRouter => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "inetRouter",
      :net => [
        ["192.168.255.1", 2, "255.255.255.252", "router-net"],
        ["192.168.50.10", 8, "255.255.255.0"]
      ]
    },

    :centralRouter => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "centralRouter",
      :net => [
        ["192.168.255.2", 2, "255.255.255.252", "router-net"],
        ["192.168.0.1", 3, "255.255.255.240", "dir-net"],
        ["192.168.0.33", 4, "255.255.255.240", "hw-net"],
        ["192.168.0.65", 5, "255.255.255.192", "mgt-net"],
        ["192.168.255.9", 6, "255.255.255.252", "office1-central"],
        ["192.168.255.5", 7, "255.255.255.252", "office2-central"],
        ["192.168.50.11", 8, "255.255.255.0"]
      ]
    },

    :centralServer => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "centralServer",
      :net => [
        ["192.168.0.2", 2, "255.255.255.240", "dir-net"],
        ["192.168.50.12", 8, "255.255.255.0"]
      ]
    },

    :office1Router => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "office1Router",
      :net => [
        ["192.168.255.10", 2, "255.255.255.252", "office1-central"],
        ["192.168.2.1", 3, "255.255.255.192", "dev1-net"],
        ["192.168.2.65", 4, "255.255.255.192", "test1-net"],
        ["192.168.2.129", 5, "255.255.255.192", "managers-net"],
        ["192.168.2.193", 6, "255.255.255.192", "office1-net"],
        ["192.168.50.20", 8, "255.255.255.0"]
      ]
    },

    :office1Server => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "office1Server",
      :net => [
        ["192.168.2.130", 2, "255.255.255.192", "managers-net"],
        ["192.168.50.21", 8, "255.255.255.0"]
      ]
    },

    :office2Router => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "office2Router",
      :net => [
        ["192.168.255.6", 2, "255.255.255.252", "office2-central"],
        ["192.168.1.1", 3, "255.255.255.128", "dev2-net"],
        ["192.168.1.129", 4, "255.255.255.192", "test2-net"],
        ["192.168.1.193", 5, "255.255.255.192", "office2-net"],
        ["192.168.50.30", 8, "255.255.255.0"]
      ]
    },

    :office2Server => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "office2Server",
      :net => [
        ["192.168.1.2", 2, "255.255.255.128", "dev2-net"],
        ["192.168.50.31", 8, "255.255.255.0"]
      ]
    }
  }

  MACHINES.each do |machine_name, machine_config|
    config.vm.define machine_name do |machine|
      machine.vm.box = machine_config[:box_name]
      machine.vm.hostname = machine_config[:vm_name]

      machine.vm.provider "virtualbox" do |vb|
        vb.memory = 768
        vb.cpus = 1
        vb.name = machine_config[:vm_name]
      end

      machine_config[:net].each do |network|
        machine.vm.network "private_network",
          ip: network[0],
          virtualbox__intnet: network[3],
          netmask: network[2],
          auto_config: true
      end

      machine.vm.provision "shell", inline: <<-SHELL
        mkdir -p /root/.ssh
        cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
      SHELL
    end
  end
end