---
- name: Install Docker and Docker Compose on Debian 12
  hosts: all
  become: true  # Выполнение от имени root
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Установка базовых зависимостей
      apt:
        name:
          - ca-certificates
          - curl
        state: present
    
    - name: Add Docker's official GPG key and the repository to Apt sources
      shell: |
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

    - name: Install the Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
