MACHINES = {
  :"debian-raid" => {
              #Какой vm box будем использовать
              :box_name => "debian/bookworm64",
              #Указываем box_version
              :box_version => "12.20240212.1",
              :cpus => 2,
              :memory => 2048,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Включаем проброс общей папки vagrant-share из домашней директории
    #config.vm.synced_folder "~/vagrant-share", "/vagrant", disabled: false
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      (0..3).each do |i|
        box.vm.disk :disk, size: "100MB", name: "disk-#{i}"
      end




#      box.vm.provision "shell", inline: <<-SHELL
#        uname -a > /vagrant/old.ver # запись версии старого ядра
#        dnf install langpacks-en glibc-all-langpacks -y # установка языкового пакета
#        yum install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
#        yum --enablerepo elrepo-kernel install kernel-ml -y
#        grub2-mkconfig -o /boot/grub2/grub.cfg
#        grub2-set-default 0
#        reboot
#      SHELL
    end
  end
end
