MACHINES = {
  :"debian-raid" => {
              #Какой vm box будем использовать
              :box_name => "generic/debian12",
              #Указываем box_version
              :box_version => "4.3.12",
              :cpus => 2,
              :memory => 2048,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Включаем проброс общей папки vagrant-share из домашней директории
    #config.vm.synced_folder "~/vagrant-share", "/vagrant", disabled: false
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      (0..3).each do |i|
        box.vm.disk :disk, size: "1GB", name: "disk-#{i}"
      end

      box.vm.provision "shell", inline: <<-SHELL
        apt update # && apt upgrade -y
        apt install -y fdisk gdisk parted mdadm # установка пакетов для работы с диском и фс
        mdadm --create /dev/md127 -l 10 -n 4 /dev/sd{b,c,d,e} 
        echo "DEVICE partitions" > /etc/mdadm/mdadm.conf 
        mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
        parted --script /dev/md127 mklabel gpt
        parted /dev/md127 mkpart primary ext4 0% 20%
        parted /dev/md127 mkpart primary ext4 20% 40%
        parted /dev/md127 mkpart primary ext4 40% 60%
        parted /dev/md127 mkpart primary ext4 60% 80%
        parted /dev/md127 mkpart primary ext4 80% 100%
        for i in $(seq 1 5)
          do
            mkfs.ext4 /dev/md127p$i
            mkdir -p /mnt/raid/part${i}
            mount /dev/md127p${i} /mnt/raid/part${i}
            echo "/dev/md127p${i} /mnt/raid/part${i}    ext4    defaults  0  0" >> /etc/fstab
          done
      SHELL
    end
  end
end
