#SPDX-License-Identifier: MIT-0
---
# tasks file for monitoring_setup
- name: Create config directory
  ansible.builtin.file:
    path: /opt/gatus
    state: directory
    mode: '0755'

- name: Copy config file
  ansible.builtin.copy:
    src: config.yaml
    dest: /opt/gatus/config.yaml
    owner: root
    group: root
    mode: '0644'

- name: Ensure gatus container is absent
  community.docker.docker_container:
    name: gatus
    state: absent

- name: Start docker gatus
  community.docker.docker_container:
    name: gatus
    image: twinproduction/gatus
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8080:8080"
    volumes:
      - /opt/gatus/config.yaml:/config/config.yaml

