## Настройка OSPF на routers
# # ==========================================================
#

# Установка FRR на routers и активация ip_forwarding
# ==========================================================\
- name: Install OSPF on routers
  import_playbook: ospf-install.yml

# Настройка routers для работы OSPF
# ==========================================================
- name: Configure OSPF on routers
  hosts: all
  become: true
  tasks:

# Установка прочих пакетов для удобства и диагностики
    - name: Install additional packages
      apt:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true

# Отключение и удаление UFW
    - name: Disable and stop UFW
      ufw:
        state: disabled
      ignore_errors: true
    - name: Remove UFW
      apt:
        name: ufw
        state: absent
      ignore_errors: true

# Останавливаем frr.service, если он запущен
    - name: Stop frr service if running
      service:
        name: frr
        state: stopped
      ignore_errors: true

# Меняем настройки daemons FRR
    - name: Configure FRR daemons
      lineinfile:
        path: /etc/frr/daemons
        regexp: '^{{ item.name }}'
        line: '{{ item.name }}={{ item.state }}'
      with_items:
        - { name: zebra, state: "yes" }
        - { name: ospfd, state: "yes" }
      notify: restart frr

# Устанавливаем настройки frr.conf
    - name: Configure FRR
      template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: '0640'
      notify: restart frr

# Перезапускаем службу frr
    - name: Restart FRR service
      service:
        name: frr
        state: restarted

  handlers:
    - name: restart frr
      service:
        name: frr
        state: restarted
