---
# docker install task
- name: Установка зависимостей
  apt:
    name:
      - ca-certificates
      - curl
    state: latest
    update_cache: yes

- name: Создание каталога для ключей
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755


- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker.list
    update_cache: yes

- name: Установка Docker компонентов
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Запуск и включение службы Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Добавление пользователя в группу docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
    create_home: no