---
# docker install task
- name: Установка зависимостей
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: yes

- name: Создание каталога для ключей
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Добавление GPG-ключа Docker
  ansible.builtin.command: >
    sh -c 'curl -fsSL https://download.docker.com/linux/debian/gpg |
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Добавление репозитория Docker
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Установка Docker компонентов
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Запуск и включение службы Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Добавление пользователя в группу docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
    create_home: no