---
# docker install task
- name: Установка зависимостей
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: latest
    update_cache: true

- name: Создание каталога для ключей
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker repository
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Установка Docker компонентов
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - python3-docker
    state: present
    update_cache: true

- name: Запуск и включение службы Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Добавление пользователя в группу docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    create_home: false
