#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql_source_setup
- name: Install python3-mysqldb
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present
  when: ansible_facts['os_family'] == 'Debian'
- name: Configure MySQL to use mysql_native_password
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    insertafter: '^\[mysqld\]'
    line: 'default-authentication-plugin=mysql_native_password'
    state: present
  notify: Restart mysql  # Перезапуск MySQL для применения изменений
- name: Changing root password ignoring when failed
  community.mysql.mysql_user:
    check_implicit_admin: true
    name: root
    password: "{{ mysql_source_setup_root_password }}"
    host: "localhost"
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  failed_when: false
- name: Create root user with all database privileges
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_source_setup_root_password }}"
    check_implicit_admin: true
    name: root
    password: "{{ mysql_source_setup_root_password }}"
    host: "%"
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
# - name: Create database user with name 'seafile' and password '12345' with all database privileges
#   community.mysql.mysql_user:
#     login_user: root
#     login_password: "{{ mariadb_master_setup_root_password }}"
#     check_implicit_admin: true
#     name: seafile
#     password: "{{ mariadb_master_setup_seafile_password }}"
#     host: "%"
#     priv: "*.*:ALL,GRANT"
#     state: present
- name: Changing bind-address in /etc/mysql/mariadb.conf.d/50-server.cnf
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart mysql
