# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/centos8s"
  config.vm.box_version = "4.3.12"
  config.vm.provider :virtualbox
  config.vm.hostname = "centos8-hw09"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network"
# Выполнение плейбука при создании ВМ
# при работающей вм выполнить vagrant provision
#  config.vm.provision "ansible" do |ansible|
#   ansible.playbook = "playbooks/find_alert_setup.yml"
#   #ansible.verbose = "-vvv"
#  end   
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
     end
  end
