---
- name: find_alert_setup
  hosts: all #centos8-hw09
  become: true
  tasks:

    - name: copy settings
      copy:
        src: files/watchlog
        dest: /etc/sysconfig/
        owner: root
        group: root
        mode: '0644'

    - name: copy logfile
      copy:
        src: files/watchlog.log
        dest: /var/log/
        owner: root
        group: root
        mode: '0644'


    - name: copy script
      copy:
        src: files/watchlog.sh
        dest: /opt/
        owner: root
        group: root
        mode: '0744'

    - name: copy service
      copy:
        src: files/watchlog.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'

    - name: copy timer
      copy:
        src: files/watchlog.timer
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd_service:
        daemon_reload: yes

    - name: Enable a timer unit
      systemd_service:
        name: watchlog.timer
        state: started
 
    - name: Enable a service unit
      systemd_service:
        name: watchlog.service
        state: started
