Vagrant.configure("2") do |config|
  MACHINES = {
    :inetRouter => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "inetRouter",
      :net => [
        ["192.168.255.1", 2, "255.255.255.252", "router-net"],
        ["192.168.50.10", 8, "255.255.255.0"]
      ]
    },

    :inetRouter2 => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "inetRouter2",
      :net => [
        ["192.168.255.13", 2, "255.255.255.252", "router2-net"],
        ["192.168.50.13", 8, "255.255.255.0"]
      ]
    },

    :centralRouter => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "centralRouter",
      :net => [
        ["192.168.255.2", 2, "255.255.255.252", "router-net"],
        ["192.168.255.14", 2, "255.255.255.252", "router2-net"],
        ["192.168.0.1", 3, "255.255.255.240", "dir-net"],
        ["192.168.50.11", 8, "255.255.255.0"]
      ]
    },

    :centralServer => {
      :box_name => "generic/ubuntu2204",
      :vm_name => "centralServer",
      :net => [
        ["192.168.0.2", 2, "255.255.255.240", "dir-net"],
        ["192.168.50.12", 8, "255.255.255.0"]
      ]
    },

  }

  MACHINES.each do |machine_name, machine_config|
    config.vm.define machine_name do |machine|
      machine.vm.box = machine_config[:box_name]
      machine.vm.hostname = machine_config[:vm_name]

      machine.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 4
        vb.name = machine_config[:vm_name]
      end

      machine_config[:net].each do |network|
        machine.vm.network "private_network",
          ip: network[0],
          virtualbox__intnet: network[3],
          netmask: network[2],
          auto_config: true
      end

      machine.vm.provision "shell", inline: <<-SHELL
        mkdir -p /root/.ssh
        cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
      SHELL
    end
  end
end