#SPDX-License-Identifier: MIT-0
---
# tasks file for backup_srv_setup
- name: Download MySQL deb package
  ansible.builtin.get_url:
    url: "https://repo.mysql.com//mysql-apt-config_0.8.34-1_all.deb"
    dest: /tmp/mysql.deb
    mode: '0644'
    validate_certs: false
    checksum: "md5:ab23dec6619a7e65e8462646936ee49f"
- name: Install mysql-apt-config
  ansible.builtin.apt:
    deb: /tmp/mysql.deb
    state: present
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install packages
  ansible.builtin.apt:
    name:
      - cron
      - rsync
      - rdiff-backup
      - mysql-client
    state: present
    update_cache: true
- name: Copy ssh key
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: '0600'
    owner: root
    group: root
- name: Copy script files
  ansible.builtin.copy:
    src: files/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
    owner: root
    group: root
  loop:
    - backup.sh
    - restore_files.sh
    - restore_databases.sh
- name: Add cron task
  ansible.builtin.cron:
    name: "Backup script"
    minute: "*/15"
    job: "/usr/local/bin/backup.sh"
    user: root
