---
- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted
