Vagrant.configure("2") do |config|
  # Базовый образ
  config.vm.box = "ubuntu/jammy64"

  # VM1 - мастер
  config.vm.define "db1" do |db1|
    db1.vm.hostname = "db1"
    db1.vm.network "private_network", ip: "192.168.56.11"
    db1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    db1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      reboot
    SHELL
  end

  # VM2 - реплика
  config.vm.define "db2" do |db2|
    db2.vm.hostname = "db2"
    db2.vm.network "private_network", ip: "192.168.56.12"
    db2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    db2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      reboot
    SHELL
  end
end