---
# Установка VPN-сервера и клиента с использованием Ansible
- name: Provision VPN Server and Client
  hosts: all
  gather_facts: yes
  become: yes
  tasks:

# Установка OpenVPN на сервере и клиенте
    - name: Install OpenVPN
      ansible.builtin.apt:
        update_cache: yes
        name:
          - openvpn
          - iperf3
          - selinux-utils
          - rsync
        state: present
        update_cache: yes
    
    - name: Disable SELinux
      command: setenforce 0
      ignore_errors: yes  # На случай если SELinux не установлен

- name: Configure OpenVPN server
  hosts: server
  become: yes
  gather_facts: yes
  tasks:
    - name: Generate static key
      command: openvpn --genkey secret /etc/openvpn/static.key
      args:
        creates: /etc/openvpn/static.key

    - name: Create server.conf
      copy:
        dest: /etc/openvpn/server.conf
        content: |
          dev tun
          ifconfig 10.10.10.1 255.255.255.0
          topology subnet
          secret /etc/openvpn/static.key
          comp-lzo
          status /var/log/openvpn-status.log
          log /var/log/openvpn.log
          verb 3

    - name: Create openvpn@.service unit
      copy:
        dest: /etc/systemd/system/openvpn@.service
        content: |
          [Unit]
          Description=OpenVPN Tunneling Application On %I
          After=network.target
          [Service]
          Type=notify
          PrivateTmp=true
          ExecStart=/usr/sbin/openvpn --cd /etc/openvpn/ --config %i.conf
          [Install]
          WantedBy=multi-user.target

    - name: Start and enable OpenVPN service
      systemd:
        name: openvpn@server
        state: started
        enabled: yes
        daemon_reload: yes

- name: Configure OpenVPN client
  hosts: client
  become: yes
  gather_facts: yes

  tasks:

    - name: Copy key using ansible.builtin.fetch + copy
      block:
        - name: Fetch key from server to control node
          fetch:
            src: /etc/openvpn/static.key
            dest: /tmp/static.key.tmp
            flat: yes
          delegate_to: server
          run_once: yes

        - name: Copy key to client
          copy:
            src: /tmp/static.key.tmp
            dest: /etc/openvpn/static.key
            owner: root
            group: root
            mode: '0600'

      always:
        - name: Cleanup temp file
          file:
            path: /tmp/static.key.tmp
            state: absent
          delegate_to: localhost
          run_once: yes

        
    - name: Create client.conf
      copy:
        dest: /etc/openvpn/server.conf
        content: |
          dev tun
          remote 192.168.56.10
          ifconfig 10.10.10.2 255.255.255.0
          topology subnet
          route 192.168.56.0 255.255.255.0
          secret /etc/openvpn/static.key
          comp-lzo
          status /var/log/openvpn-status.log
          log /var/log/openvpn.log
          verb 3

    - name: Create openvpn@.service unit
      copy:
        dest: /etc/systemd/system/openvpn@.service
        content: |
          [Unit]
          Description=OpenVPN Tunneling Application On %I
          After=network.target
          [Service]
          Type=notify
          PrivateTmp=true
          ExecStart=/usr/sbin/openvpn --cd /etc/openvpn/ --config %i.conf
          [Install]
          WantedBy=multi-user.target

    - name: Start and enable OpenVPN service
      systemd:
        name: openvpn@server
        state: started
        enabled: yes
        daemon_reload: yes
