---
# tasks file for install_packages
#Установка приложений на RedHat-based системах
- name: install software on CentOS
  yum:
    name:
      - vim
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true
  when: (ansible_os_family == "RedHat")

#Установка приложений на Debian-based системах
- name: install software on Debian-based
  apt:
    name: 
      - vim
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true
  when: (ansible_os_family == "Debian")
